# Generated by Django 2.0.3 on 2018-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', related_query_name='movie', to='main.Genre'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='movies',
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='main.Movie'),
        ),
    ]
