# Generated by Django 2.0.3 on 2018-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180318_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default board', max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='movies', related_query_name='movie', to='main.Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', related_query_name='movie', to='main.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='main.Rating'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddField(
            model_name='board',
            name='movies',
            field=models.ManyToManyField(related_name='boards', related_query_name='board', to='main.Movie'),
        ),
    ]
